spring:
  data:
    neo4j:
      username: neo4j
      password: root

  jackson:
    serialization:
      indent_output: true

#TODO Fix token problem
vk:
  app_id: 6183857
  client_secret: wtXph7bLCsrEiakszeKj