spring:
  data:
    neo4j:
      username: neo4j
      password: test

  jackson:
    serialization:
      indent_output: true

app:
  url: http://localhost:8080

vk:
  app_id: 6183857
  client_secret: wtXph7bLCsrEiakszeKj

neo4j:
  uri: bolt://database:7687
  username: neo4j
  password: test

core:
  partitionSize: 24

logging:
  file: application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        web: ERROR
    com:
      eltech:
        sh: DEBUG
